learnguitar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
path('', include('pages.urls')),
path('posts/', include('posts.urls')),
path('admin/', admin.site.urls),
path('users/', include('users.urls')),
path('users/', include('django.contrib.auth.urls')),
path('media/', include('media.urls')),
path('bmedia/', include('media.burls')),
path('emedia/', include('media.eurls')),
path('ihmedia/', include('media.ihurls')),
path('lvmedia/', include('media.lvurls')),
]

media/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('<int:pk>/', views.MediaDetailView.as_view(), name='media_detail'),
	path('', views.MediaListView.as_view(), name='media_list'),
	
]
	

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.HomePageView.as_view(), name='home'),
path('about/', views.AboutPageView.as_view(), name='about')

]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.PostListView.as_view(), name='post_list'),
	path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
	path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
	path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
	path('new/', views.PostCreateView.as_view(), name='post_new'),
] 

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('signup/', views.SignUp.as_view(), name='signup'),
]

media/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse





class Media(models.Model):
	EffSection = models.CharField(max_length=50)	
	IHSection = models.CharField(max_length=50)		
	BegSection = models.CharField(max_length=50)	
	Efficiency = models.IntegerField(blank=True, null=True)	
	InformationHierarchy = models.IntegerField(blank=True, null=True)	
	Beginner = models.IntegerField(blank=True, null=True)	
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
	)
	title = models.CharField(max_length=200)	
	media_url = models.CharField(max_length=280)
	info = models.CharField(max_length=2800)	
	date = models.DateTimeField(auto_now_add=True)
	
	

	
	
	def get_absolute_url(self):

		return reverse('media_detail', args=[str(self.id)])

	def __str__(self):
       		return self.title

	

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Post(models.Model):
	title = models.CharField(max_length=200)	
	message = models.CharField(max_length=280)
	date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
	)
	
	def get_absolute_url(self):

		return reverse('post_detail', args=[str(self.id)])

	def __str__(self):
       		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	comment = models.CharField(max_length=140)
	author = models.ForeignKey(
	settings.AUTH_USER_MODEL,
	on_delete=models.CASCADE,
	)

	def get_absolute_url(self):
		return reverse('post_list')

	def __str__(self):
		return self.comment

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager



class CustomUserManager(UserManager):
	pass

class CustomUser(AbstractUser):
	objects = CustomUserManager()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):


	class Meta(UserCreationForm.Meta):
		model = CustomUser
		fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
	class Meta:
		model = CustomUser
		fields = UserChangeForm.Meta.fields

media/views.py
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.utils import timezone
from django.core.paginator import Paginator


from . import models


class MediaListView(ListView):
	model = models.Media
	template_name = 'media_list.html'
	paginate_by = 5  # if pagination is desired
	
	
	


	
class MediaDetailView(DetailView):
	model = models.Media
	template_name = 'media_detail.html'



class bMediaListView(ListView):
	model = models.Media
	template_name = 'bmedia_list.html'
	paginate_by = 5  # if pagination is desired
	
	def get_queryset(self):
        	return models.Media.objects.order_by('Beginner')
	
class eMediaListView(ListView):
	model = models.Media
	template_name = 'emedia_list.html'
	paginate_by = 5  # if pagination is desired
	
	def get_queryset(self):
        	return models.Media.objects.order_by('Efficiency')


class ihMediaListView(ListView):
	model = models.Media
	template_name = 'ihmedia_list.html'
	paginate_by = 5  # if pagination is desired
	
	def get_queryset(self):
        	return models.Media.objects.order_by('InformationHierarchy')


class lvMediaListView(ListView):
	model = models.Media
	template_name = 'lvmedia_list.html'
	paginate_by = 5  # if pagination is desired
	
	def get_queryset(self):
        	return models.Media.objects.filter(EffSection='LV').order_by('-Efficiency')

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
	template_name = 'home.html'

class AboutPageView(TemplateView):
    template_name = 'about.html'

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from . import models




class PostListView(LoginRequiredMixin, ListView): # new
	model = models.Post
	template_name = 'post_list.html'
	login_url = 'login'

class PostCreateView(LoginRequiredMixin, CreateView):
	model = models.Post
	template_name = 'post_new.html'
	fields = ['title', 'message']
	login_url = 'login'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)



class PostDetailView(LoginRequiredMixin, DetailView):
	model = models.Post
	template_name = 'post_detail.html'
	login_url = 'login'

class PostUpdateView(LoginRequiredMixin, UpdateView): # new
	model = models.Post
	fields = ['title', 'message']
	template_name = 'post_edit.html'
	login_url = 'login' # new

class PostDeleteView(LoginRequiredMixin, DeleteView): # new
	model = models.Post
	template_name = 'post_delete.html'
	success_url = reverse_lazy('posts')
	login_url = 'login' # new

users/views.py
# users/views.py
from django.urls import reverse_lazy
from django.views import generic

from .forms import CustomUserCreationForm

class SignUp(generic.CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'signup.html'

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
<h1>Thanks for Visiting</h1>
<p>Feel Free to Contact: <b>TheFatKat</b> on Discord</p>

</div>
<div id="steemit-profile"></div>
<script src="https://cdn.steemjs.com/lib/latest/steem.min.js"></script>
<script src="https://mktcode.github.io/steemit-widgets/assets/js/steemit-widgets.min.js"></script>
<script>
  steemitWidgets.profile({
    user: 'learnguitar',
    element: 'steemit-profile',
    template: '<article class="uk-comment"><header class="uk-comment-header uk-text-left" style="background: url(${COVERIMAGE}) center center; background-size: cover;"><div class="uk-comment-avatar" style="background: url(${IMAGE}) center center; background-size: cover; width: 50px; height: 50px; border-radius: 36px;"></div><h4 class="uk-comment-title"><a href="https://steemit.com/@${USER}">@${USER}</a> <div class="uk-badge uk-badge-notification">${REPUTATION}</div></h4><div class="uk-comment-meta"><a href="${WEBSITE}">${WEBSITE}</a><br>${ABOUT}</div></header><div class="uk-comment-body uk-text-center"><div class="uk-grid"><div class="uk-width-1-3"><b>${POSTCOUNT}</b><br><sup>Posts</sup></div><div class="uk-width-1-3"><b>${FOLLOWERS}</b><br><sup>Followers</sup></div><div class="uk-width-1-3"><b>${FOLLOWING}</b><br><sup>Following</sup></div><div class="uk-width-1-2 uk-text-small uk-text-left">Voting Power: ${VOTINGPOWER} %</div><div class="uk-width-1-2 uk-text-small uk-text-right"><i class="uk-icon-map-marker"></i> ${LOCATION}</div></div></div></article><style>#steemit-profile{border-radius:6px;max-width:360px;background:#ccff99;border:4px solid #4696e5}#steemit-profile .uk-comment-header{margin-bottom:5px;border:none;border-bottom-left-radius:0;border-bottom-right-radius:0}#steemit-profile .uk-comment-avatar{background-position:center center;background-size:cover;width:50px;height:50px}#steemit-profile .uk-comment-meta,#steemit-profile .uk-comment-meta a,#steemit-profile .uk-comment-title a{color:#fff}#steemit-profile .uk-comment-body{color:#999;font-size: 18px;line-height: 24px}</style>',
    reputationPrecision: 1
  });
</script>


{% endblock %}

templates/base.html
<!doctype html>



<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-t\
o-fit=no">
<!-- Bootstrap CSS -->
 
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<title{% block title %}FatKat's LearnGuitar{% endblock title %}</title>


</head>





<header>


<nav class="navbar navbar-inverse">
<div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">FatKat's Learn Guitar</a>
    </div>
  
    <ul class="navbar-nav mr-auto">


 <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">





 <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
      </li>

<li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About <span class="sr-only"></span></a>
      </li>

 <li class="nav-item">
        <a class="nav-link" href="{% url 'lvmedia_list' %}">Weekly Live Streams <span class="sr-only"></span></a>
      </li>


   <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Taxonomies</a>
    <div class="dropdown-menu navbar-inverse">
     
      <a class="dropdown-item" href="{% url 'bmedia_list' %}">Beginner</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'emedia_list' %}">Efficiency</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'ihmedia_list' %}">Information Hierarchy</a>
    </div>
  </li>



</ul>
</div>
</nav>
</header>

<header>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1229807192740071",
    enable_page_level_ads: true
  });
</script>
</header>


<head>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1229807192740071",
    enable_page_level_ads: true
  });
</script>
</head>

<style type="text/css">
   body { background: #ffff99 !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
.dropdown-menu a{
    color: #ccff99 !important;


</style>







<body>


<div class="container">
<div class="row">
 <div class="col align-self-center">






<a class="btn btn-primary" href="https://www.facebook.com/fatkatband/">Facebook</a>

<a class="btn btn-warning" href="https://www.steemit.com/@learnguitar" role="button">Steem</a>



<a class="btn btn-danger" href="https://www.youtube.com/channel/UCNNfELRHoVujxGr5SpCyXBw">Youtube</a>

<a class="btn btn-info" href="https://www.twitter.com/fatkatband" role="button">Twitter</a>
</div>


<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
<a class="navbar-brand" href="{% url 'home' %}">Learn Guitar</a>
{% if user.is_authenticated %}
 <ul class="list-unstyled">
<li class="nav-item"><a href="{% url 'post_new' %}">+ New</a></li>
</ul>
{% endif %}





<div class="collapse navbar-collapse" id="navbarCollapse">
{% if user.is_authenticated %}
 <ul class="list-unstyled">
<li class="nav-item">
<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-to\
ggle="dropdown" aria-haspopup="true" aria-expanded="false">
{{ user.username }}
</a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="us\
erMenu">
<a class="dropdown-item" href="{% url 'password_change' %}">Chan\
ge password</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
</div>
</li>
</ul>
{% else %}
<form class="form-inline ml-auto">
<a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in
</a>
<a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
</form>
{% endif %}
</div>
</nav>
<div class="container">
{% block content %}
{% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sh\
a384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorig\
in="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/pop\
per.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakF\
PskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.mi\
n.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+\
76PVCmYl" crossorigin="anonymous"></script>
</body>
<footer>
  </div>



  <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>

        <p>All entity owned content released under <a href="http://unlicense.org/">The Unlicense</a></p>
      </div>


     
      </footer>

</html>

templates/bmedia_list.html
{% extends 'base.html' %}

{% block title %}Media{% endblock %}

{% block content %}
 	


     
{% for post in object_list %}



 <div class="card-group">

	<div class="card">
	<div class="card-header">
	<div class="media-entry">
	<h2><a href="{% url 'media_detail' post.pk %}">{{ post.title }}</a></h2>
				<span class="font-weight-bold">{{ post.author }}</span> &middot; <span class="text-muted">{{ post.date }}</span>
	</div>		
<div>
			<div class="card-body">

<div class="container">

	
<div class="col-sm-6">


<div class="embed-responsive embed-responsive-16by9">
<iframe src={{ post.media_url }} frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>



</div>	
<div class="col-sm-6">

<span class="font-weight-bold">{{ post.info }}</span>
</div>	
			
</div>	
		</div>
			</div>

   

        {% endfor %}


 <div class="container">

<h1><a href="/media/6/">Beginner Taxonomy </a></h1>
  <div class="col-md-3">
 <ul class="list-unstyled">
<h3><a href="/media/24/">Make It Interesting</a></h3>
	<li><a href="/media/24/">4 Basic Chord</a></li>
        	<li><a href="/media/25/">C Major Across Fret Board</a></li>
        	<li><a href="/media/26/">C Minor Across Fret Board</a></li>
        	<li><a href="/media/27/">C Diminished Across Fret Board</a></li>
        	<li><a href="/media/28/">C Power Across Fret Board</a></li>
        	<li><a href="/media/50/">C Ionian Pentatonic </a></li>
        	<li><a href="/media/51/">D Dorian Pentatonic</a></li>
        	<li><a href="/media/52/">E Phrygian Pentatonic</a></li>
        	<li><a href="/media/53/">G Mixolydian Pentatonic</a></li>
        	<li><a href="/media/54/">A Aeolian Pentatonic</a></li>

<h3><a href="/media/1/">How It Works</a></h3>
        	<li><a href="/media/1/">Ordered Lists</a></li>
        	<li><a href="/media/2/">All Notes</a></li>
        	<li><a href="/media/3/">All Intervals</a></li>
        	<li><a href="/media/4/">Circle of 4ths</a></li>
        	
<h3><a href="/media/5/">Insights</a></h3>
	<li><a href="/media/5/">Taxonomies</a></li>        
	<li><a href="/media/6/">Information Hierarchy Taxonomy</a></li>
        	<li><a href="/media/7/">Beginner Taxonomy</a></li>
        	<li><a href="/media/8/">Efficiency Taxonomy</a></li>
        	<li><a href="/media/9/">Perspectives General</a></li>
        	<li><a href="/media/10/">Perspectives Fret</a></li>

</ul>
       </div>
<div class="col-md-3">
<ul class="list-unstyled">
<li><a href="/media/11/">Perspectives Spacing</a></li>
        	<li><a href="/media/12/">Perspectives Recommended Fingering</a></li>
        	<li><a href="/media/13/">Perspectives Notes</a></li>
        	<li><a href="/media/14/">Perspectives Interval</a></li>
        	<li><a href="/media/15/">Maxims</a></li>
        	<li><a href="/media/16/">Maxim 1</a></li>
        	<li><a href="/media/17/">Maxim 2</a></li>
        	<li><a href="/media/18/">Heuristics General</a></li>
        	<li><a href="/media/19/">Heuristic 1</a></li>
        	<li><a href="/media/20/">Heuristic 2</a></li>
        	<li><a href="/media/21/">Heuristic 3</a></li>
        	<li><a href="/media/22/">Heuristic 4</a></li>
        	<li><a href="/media/23/">Heuristic 5</a></li>

<h3><a href="/media/29/">Diving Deeper</a></h3>
        	<li><a href="/media/29/">The Modes</a></li>
        	<li><a href="/media/30/">Ionian</a></li>
        	<li><a href="/media/31/">Dorian</a></li>
        	<li><a href="/media/32/">Phrygian</a></li>
        	<li><a href="/media/33/">Lydian</a></li>
        	<li><a href="/media/34/">Mixolydian</a></li>
        	<li><a href="/media/35/">Aeolian</a></li>
        	<li><a href="/media/36/">Locrian</a></li>
<li><a href="/media/37/">C Ionian</a></li>
        	<li><a href="/media/38/">D Dorian</a></li>
        	<li><a href="/media/39/">E Phrygian</a></li>
        	<li><a href="/media/40/">F Lydian</a></li>
        	<li><a href="/media/41/">G Mixolydian</a></li>
</ul>
       </div>
<div class="col-md-3">
<ul class="list-unstyled">
	
        	<li><a href="/media/42/">A Aeolian</a></li>
        	<li><a href="/media/43/">B Locrian</a></li>

<h3><a href="/media/44/">Bottom of the Sea</a></h3>
        	<li><a href="/media/44/">Interval Walls</a></li>
        	<li><a href="/media/45/">Interval Walls Ionian</a></li>
        	<li><a href="/media/46/">Interval Walls Dorian</a></li>
        	<li><a href="/media/47/">Interval Walls Lydian</a></li>
        	<li><a href="/media/48/">Interval Walls Mixolydian</a></li>
        	<li><a href="/media/49/">Interval Walls Aeolian</a></li>
        	
<h3><a href="/media/55/">Common Patterns</a></h3>
	<li><a href="/media/55/">Common Interval Patterns Types</a></li>
        	<li><a href="/media/56/">Common Interval Patterns 1 4 5</a></li>
        	<li><a href="/media/57/">Common Interval Patterns 1 6 2 5</a></li>
        	<li><a href="/media/58/">Common Interval Patterns 1 5 6</a></li>
        	<li><a href="/media/59/">Common Interval Patterns 1 6 4 5</a></li>
        	<li><a href="/media/60/">Common Interval Patterns 6 5 4</a></li>	
<li><a href="/media/61/">Common Interval Patterns 1 5 6 4</a></li>
        	<li><a href="/media/62/">Common Strumming Patterns Types</a></li>
        	<li><a href="/media/63/">Common Strumming Patterns Down Strokes</a></li>  

<li><a href="/media/64/">Common Strumming Patterns Reggae</a></li>
        	<li><a href="/media/65/">Common Strumming Patterns Plucking</a></li>
</ul>

       </div>
      <div class="col-md-3">
<ul class="list-unstyled">
 
	
        	
<h3><a href="/media/66/">Cool Exercises</a></h3>
	<li><a href="/media/66/">Arpeggio Exercises</a></li>
        	<li><a href="/media/67/">Arpeggio Exercises Ionian</a></li>
        	<li><a href="/media/68/">Arpeggio Exercises Dorian</a></li>
        	<li><a href="/media/69/">Arpeggio Exercises Phrygian</a></li>
        	<li><a href="/media/70/">Arpeggio Exercises Lydian</a></li>
        	<li><a href="/media/71/">Arpeggio Exercises Mixolydian</a></li>
        	<li><a href="/media/72/">Arpeggio Exercises Aeolian</a></li>
        	<li><a href="/media/73/">Arpeggio Exercises Locrian</a></li>
        	<li><a href="/media/74/">Chord Construction Exercises</a></li>
        	<li><a href="/media/75/">Chord Construction 1 3 5 E String</a></li>
        	<li><a href="/media/76/">Chord Construction 1 3 5 A String</a></li>
        	<li><a href="/media/77/">Chord Construction 1 3 5 D String</a></li>
        	<li><a href="/media/78/">Chord Construction 3 5 1 E String</a></li>
        	<li><a href="/media/79/">Chord Construction 3 5 1 A String</a></li>
        	<li><a href="/media/80/">Chord Construction 3 5 1 D String</a></li>
        	<li><a href="/media/81/">Chord Construction 5 1 3 E String</a></li>
        	<li><a href="/media/82/">Chord Construction 5 1 3 A String</a></li>
        	<li><a href="/media/83/">Chord Construction 5 1 3 D String</a></li>
            <p><a class="btn btn-success" href="/media/7/" role="button">View details &raquo;</a></p>
</ul>
       </div>
        
   

      

     
    </div> <!-- /container -->


 




             
  <ul class="pagination">
    {% if page_obj.has_previous %}
	<li><a href="/bmedia?page={{ page_obj.previous_page_number }}">&laquo;</a></li>

    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}

{% if page_obj.number >= 4 %}
 <li><a href="/bmedia?page={{ 1 }}">first</a></li>
  {% endif %}




 {% for n in page_obj.paginator.page_range %}
  {% if page_obj.number == n %}
    <li class="page-item active">
      <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
    </li>
  {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
    <li class="page-item"><a class="page-link" href="/bmedia?page={{ n }}">{{ n }}</a></li>
  {% endif %}
{% endfor %}

 




 {% if page_obj.has_next %}
     
     <li><a href="/bmedia?page={{ page_obj.paginator.num_pages }}">last</a></li>     
     <li><a href="/bmedia?page={{ page_obj.next_page_number }}">&raquo;</a></li>
 
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>


    


{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div style="background:#99ff66 !important" class="jumbotron" bg-dark>

<h1 class="display-4">FatKat's Learn Guitar</h1>
<p class="lead">All entity owned content released into the public domain under <a href="http://unlicense.org/">The Unlicense</a></p>
<p class="lead">
<a class="btn btn-primary btn-lg" href="/emedia/" role="button"\
>View All Videos</a>
</p>
<div class="text-center">

  <img src="https://cdn.pixabay.com/photo/2016/05/30/09/57/guitar-1424478__340.png" class="rounded" alt="...">



  <img src="https://cdn.pixabay.com/photo/2017/10/16/21/54/breaking-2858673__340.png" class="rounded" alt="...">
</div>


</div>
{% if user.is_authenticated %}


	Hi {{ user.username }}!
	<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
	<p>You are not logged in</p>
	<a href="{% url 'login' %}">login</a> |
	<a href="{% url 'signup' %}">signup</a>





{% endif %}
{% endblock %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
	<h1>Delete</h1>
	<form action="" method="post">{% csrf_token %}
		<p>Are you sure you want to delete "{{ post.message }}"?</p>
		<button class="btn btn-danger ml-2" type="submit">Confirm</button>
	</form>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="post-entry">
	<h1>{{object.title}}</h1>	
	<h2>{{ object.message }}</h2>
		<p>Author: {{ object.author }}</p>
		<p>{{ object.date }}</p>
	</div>

	<p><a href="{% url 'post_edit' post.pk %}">Edit</a> | <a href="{% url 'post_delete' post.pk %}">Delete</a></p>

	<p>Back to <a href="{% url 'post_list' %}">All Messages</a>.</p>

{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}

	{% for post in object_list %}

		<div class="card">
			<div class="card-header">
				<div class="post-entry">
				<h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
				<span class="font-weight-bold">{{ post.author }}</span> &middot; 			<span class="text-muted">{{ post.date }}</span>
			</div>		
			<div class="card-body">
				<p>{{ post.message }}</p>
				<a href="{% url 'post_edit' post.pk %}">Edit</a> | <a href="{% url 'post_delete' post.pk %}">Delete</a>
			</div>
			</div>
			<div class="card-footer">
				{% for comment in post.comment_set.all %}
					<p>
					<span class="font-weight-bold">{{ comment.author }} &middot;</span>
					{{ comment }}
					</p>
				{% endfor %}
			</div>
			</div>
			
			<br />
{% endfor %}
{% endblock content %}